XAUTH_KEYS_="$(xauth list $HOST/unix:0)"
XSOCK=/tmp/.X11-unix
XAUTH=/tmp/.docker.xauth
CAM=/dev/video1

build:
	virtualenv cv2pose
#	docker build . -t python-pose

run:
#	docker run \
#		--rm \
#		-it \
#		-e DISPLAY=${DISPLAY} \
#		-e CAM=${CAM} \
#		--device=${CAM}:${CAM} \
#		-v ${XSOCK}:${XSOCK} \
#		-v ${XAUTH}:${XAUTH} \
#		python-pose
